In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('Titanic-Dataset.csv')
Y = dataset.iloc[: , 1].values
X = dataset.iloc[: ,[2,4,5,6,7] ].values

In [ ]:
print(X)

[[3 'male' 22.0 1 0]
 [1 'female' 38.0 1 0]
 [3 'female' 26.0 0 0]
 ...
 [3 'female' nan 1 2]
 [1 'male' 26.0 0 0]
 [3 'male' 32.0 0 0]]


In [ ]:
Y = Y.reshape(len(Y),1)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 3 22.0 1 0]
 [1.0 0.0 1 38.0 1 0]
 [1.0 0.0 3 26.0 0 0]
 ...
 [1.0 0.0 3 nan 1 2]
 [0.0 1.0 1 26.0 0 0]
 [0.0 1.0 3 32.0 0 0]]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[: , 3:4])
(X[: , 3:4]) = imputer.transform(X[: , 3:4])

In [ ]:
print(X[: , 3:4])

In [ ]:
print(X)

[[0.0 1.0 3 22.0 1 0]
 [1.0 0.0 1 38.0 1 0]
 [1.0 0.0 3 26.0 0 0]
 ...
 [1.0 0.0 3 29.69911764705882 1 2]
 [0.0 1.0 1 26.0 0 0]
 [0.0 1.0 3 32.0 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train ,X_test , Y_train , Y_test = train_test_split(X,Y ,test_size =0.2) 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train , Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_pred.reshape(len(y_pred),1)) , 1 ))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test , y_pred)
print(cm)

[[89 16]
 [28 46]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred)

0.7541899441340782